### ISSUE TITLE
[bug]Unknown column '_tidb_rowid'

### ISSUE THREAD

**Issue by shiyuhang0** [JaySon-Huang/tiflash-ctl#8]
it seems tiflash-ctl only support table without pk?
i run `./tiflash-ctl check consistency --tidb_ip <ip> --tidb_port <port> --database kol --table  kol_profile_interest_model > check.log 2>&1` with table have pk. then the error occurs `Error: Error 1054: Unknown column '_tidb_rowid' in `

**Comment by JaySon-Huang** [comment]
@shiyuhang0  `check consistency` now does not work for clustered index table.
By now it only works for the tables that contain an int-like primary key. It is `_tidb_rowid` by default, or user-defined an int-like primary key (by the `--row_id_col_name` option).

And now we only define "consistency" as the number of rows are the same between TiKV and TiFlash.
